---
- name: download zookeeper
  get_url:
    url: '{{ zookeeper_download_url }}'
    dest: '/usr/local/src/zookeeper-{{ zookeeper_version }}.tar.gz'

- name: unarchive tarball
  unarchive:
    src: '/usr/local/src/zookeeper-{{ zookeeper_version }}.tar.gz'
    dest: '/opt/'
    creates: '/opt/zookeeper-{{ zookeeper_version }}'
    copy: false

- name: link install directory
  file:
    src: '/opt/zookeeper-{{ zookeeper_version }}'
    path: '{{ zookeeper_install_dir }}'
    state: link
