---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-1
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    pre_build_image: true
  - name: instance-2
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    pre_build_image: true
  - name: instance-3
    image: geerlingguy/docker-ubuntu1604-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cpu_period: 100000
    cpu_quota: 50000
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: cluster
verifier:
  name: testinfra
  lint:
    name: flake8
